apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  BACKEND_URL: "http://${BACKEND_SERVICE_NAME}-service:${BACKEND_SERVICE_PORT}"
  DOMAIN_NAME: "${DOMAIN_NAME}"
  ENVIRONMENT: "${ENVIRONMENT}"
  JAVA_OPTS: "-Xmx${JAVA_MAX_HEAP} -Xms${JAVA_MIN_HEAP} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  CACHE_IMPLEMENTATION: "redis"
  SPRING_DATA_REDIS_HOST: "${REDIS_HOST}"
  SPRING_DATA_REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${BACKEND_SERVICE_NAME}-config
data:
  SERVER_PORT: "${BACKEND_SERVICE_PORT}"
  SPRING_PROFILES_ACTIVE: "${BACKEND_SERVICE_NAME}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CACHE_UPDATER_NAME}-config
data:
  SERVER_PORT: "${CACHE_UPDATER_PORT}"
  SPRING_PROFILES_ACTIVE: "${CACHE_UPDATER_NAME}"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  github.tokens: "${GH_API_TOKENS}"
  linkedin.client.id: "${LINKEDIN_CLIENT_ID}"
  linkedin.client.secret: "${LINKEDIN_CLIENT_SECRET}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "${NODE_ENV:-production}"
  API_TIMEOUT: "${API_TIMEOUT:-30000}" 