apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: major-league-github.flamingo.cx
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: web-service-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80