apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "${DOMAIN_NAME}-ip"
    ingress.gcp.kubernetes.io/managed-certificates: "${DOMAIN_NAME}-cert"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: ${DOMAIN_NAME}.${DOMAIN_SUFFIX}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ${WEB_SERVICE_NAME}-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80