apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "main-ingress-ip"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: "main-ingress-ssl-cert"
spec:
  tls:
  - hosts:
    - major-league-github.flamingo.cx
    secretName: main-ingress-ssl-cert
  rules:
  - host: major-league-github.flamingo.cx
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80