apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 8080;
            server_name _;
            
            # Health check endpoint for GKE load balancer
            location /healthz {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Redirect all other traffic
            location / {
                return 301 https://REDIRECT_TARGET_PLACEHOLDER$request_uri;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-service
  labels:
    app: redirect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-service
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      initContainers:
      - name: config-substitution
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          sed 's|REDIRECT_TARGET_PLACEHOLDER|'"${REDIRECT_TARGET}"'|g' /original-config/nginx.conf > /config/nginx.conf
          echo "Redirect target set to: ${REDIRECT_TARGET}"
          cat /config/nginx.conf
        env:
        - name: REDIRECT_TARGET
          value: "${DOMAIN_NAME}.${DOMAIN_SUFFIX}"
        volumeMounts:
        - name: original-config
          mountPath: /original-config
        - name: processed-config
          mountPath: /config
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: processed-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: original-config
        configMap:
          name: redirect-nginx-config
      - name: processed-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  labels:
    app: redirect-service
spec:
  selector:
    app: redirect-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP