apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 8080;
            server_name _;
            
            # Health check endpoint for GKE load balancer
            location /healthz {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Redirect all other traffic
            location / {
                return 301 https://${DOMAIN_NAME}.${DOMAIN_SUFFIX}$request_uri;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-service
  labels:
    app: redirect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-service
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: nginx-config
        configMap:
          name: redirect-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: redirect-service
  labels:
    app: redirect-service
spec:
  selector:
    app: redirect-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP